#!/usr/bin/env node
/**
 * db-types — deterministic TypeScript types from the local schema.
 *
 * `generate` introspects the running local database (scripts/db-local.mjs)
 * and writes src/data/supabase/database.types.ts in the supabase-js
 * Database shape. `check` regenerates to a temporary buffer and fails when
 * the committed file has drifted from the schema.
 *
 * `supabase gen types` is preferred where Docker is available (it shells
 * into a postgres-meta container); this script produces the same shape for
 * the tables Milestone 0 uses, from information_schema, with a stable
 * ordering so output is reproducible byte-for-byte.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(appRoot, 'src', 'data', 'supabase', 'database.types.ts');
const PG_BIN = process.env.HIVE_PG_BIN ?? '/usr/lib/postgresql/16/bin';
const PORT = process.env.HIVE_PG_PORT ?? '55433';
const DB = 'hive_local';
const PG_USER = 'hivepg';

const INTROSPECTION_SQL = `
select coalesce(json_agg(t order by t.table_name), '[]'::json) from (
  select tt.table_name,
    (select json_agg(json_build_object(
        'name', c.column_name,
        'udt', c.udt_name,
        'nullable', c.is_nullable = 'YES',
        'hasDefault', c.column_default is not null or c.is_identity = 'YES'
      ) order by c.ordinal_position)
      from information_schema.columns c
      where c.table_schema = 'public' and c.table_name = tt.table_name) as columns
  from information_schema.tables tt
  where tt.table_schema = 'public' and tt.table_type = 'BASE TABLE'
) t;
`;

export function tsTypeFor(udt) {
  switch (udt) {
    case 'uuid':
    case 'text':
    case 'varchar':
    case 'bpchar':
    case 'timestamptz':
    case 'timestamp':
    case 'date':
      return 'string';
    case 'int2':
    case 'int4':
    case 'int8':
    case 'float4':
    case 'float8':
    case 'numeric':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'jsonb':
    case 'json':
      return 'Json';
    default:
      return 'string';
  }
}

export function renderTypes(tables) {
  const lines = [];
  lines.push('/** Generated by scripts/db-types.mjs from the local schema.');
  lines.push(' * Do not edit by hand — run `npm run db:types` after a migration');
  lines.push(' * and commit the result; `npm run db:types:check` fails on drift. */');
  lines.push('');
  lines.push('export type Json =');
  lines.push('  | string');
  lines.push('  | number');
  lines.push('  | boolean');
  lines.push('  | null');
  lines.push('  | { [key: string]: Json | undefined }');
  lines.push('  | Json[];');
  lines.push('');
  lines.push('export interface Database {');
  lines.push('  public: {');
  lines.push('    Tables: {');
  for (const table of tables) {
    lines.push(`      ${table.table_name}: {`);
    lines.push('        Row: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      lines.push(`          ${col.name}: ${base}${col.nullable ? ' | null' : ''};`);
    }
    lines.push('        };');
    lines.push('        Insert: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      const optional = col.nullable || col.hasDefault;
      lines.push(
        `          ${col.name}${optional ? '?' : ''}: ${base}${col.nullable ? ' | null' : ''};`,
      );
    }
    lines.push('        };');
    lines.push('        Update: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      lines.push(`          ${col.name}?: ${base}${col.nullable ? ' | null' : ''};`);
    }
    lines.push('        };');
    lines.push('        Relationships: [];');
    lines.push('      };');
  }
  lines.push('    };');
  lines.push('    Views: Record<string, never>;');
  lines.push('    Functions: Record<string, never>;');
  lines.push('    Enums: Record<string, never>;');
  lines.push('    CompositeTypes: Record<string, never>;');
  lines.push('  };');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function introspect() {
  const args = [
    '-h', '127.0.0.1', '-p', PORT, '-U', PG_USER, '-d', DB,
    '-At', '-v', 'ON_ERROR_STOP=1', '-c', INTROSPECTION_SQL,
  ];
  const direct =
    typeof process.getuid === 'function' && process.getuid() === 0
      ? spawnSync('runuser', ['-u', PG_USER, '--', path.join(PG_BIN, 'psql'), ...args], {
          encoding: 'utf8',
        })
      : spawnSync(path.join(PG_BIN, 'psql'), args, { encoding: 'utf8' });
  if (direct.status !== 0) {
    console.error(direct.stderr ?? '');
    console.error(
      'db-types: could not reach the local database. Run `node scripts/db-local.mjs reset` first.',
    );
    process.exit(1);
  }
  return JSON.parse(direct.stdout.trim());
}

const command = process.argv[2];
if (command === 'generate') {
  const rendered = renderTypes(introspect());
  writeFileSync(OUTPUT, rendered);
  console.log(`db-types: wrote ${path.relative(appRoot, OUTPUT)}`);
} else if (command === 'check') {
  const rendered = renderTypes(introspect());
  let committed = '';
  try {
    committed = readFileSync(OUTPUT, 'utf8');
  } catch {
    console.error('db-types: committed types file is missing');
    process.exit(1);
  }
  if (committed !== rendered) {
    console.error('db-types: committed database.types.ts has drifted from the schema');
    process.exit(1);
  }
  console.log('db-types: committed types match the schema');
} else {
  console.error('usage: db-types.mjs <generate|check>');
  process.exit(1);
}
