#!/usr/bin/env node
/**
 * db-types — deterministic TypeScript types from the local schema.
 *
 * `generate` introspects the running local database and writes
 * src/data/supabase/database.types.ts in the supabase-js Database shape.
 * `check` regenerates to a temporary buffer and fails when the committed
 * file has drifted from the schema.
 *
 * `supabase gen types` is preferred where Docker is available (it shells
 * into a postgres-meta container); this script produces the same shape for
 * the tables and the public functions HIVE uses, from the catalog, with a
 * stable ordering so output is reproducible byte-for-byte.
 *
 * Three ways to reach the database:
 *   0. a hosted project, when HIVE_DB_URL names it (2026-09-29): the CLI
 *      stack's container supplies the psql client, the connection travels
 *      as libpq environment variables passed through by name, and the URL
 *      (its password included) is never printed and never on a command
 *      line;
 *   1. the plain-PostgreSQL lane (scripts/db-local.mjs): psql at
 *      HIVE_PG_BIN against 127.0.0.1:HIVE_PG_PORT;
 *   2. the pinned CLI stack: `docker exec` into its database container
 *      (supabase_db_<project_id> from supabase/config.toml), which is the
 *      lane on a Windows desktop, where no psql binary exists on the host
 *      (2026-09-28).
 * HIVE_DB_LANE=cli or HIVE_DB_LANE=local forces one of the local lanes.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(appRoot, 'src', 'data', 'supabase', 'database.types.ts');
const PG_BIN = process.env.HIVE_PG_BIN ?? '/usr/lib/postgresql/16/bin';
const PORT = process.env.HIVE_PG_PORT ?? '55433';
const DB = 'hive_local';
const PG_USER = 'hivepg';
const isWindows = process.platform === 'win32';

const TABLES_SQL = `
select coalesce(json_agg(t order by t.table_name), '[]'::json) from (
  select tt.table_name,
    (select json_agg(json_build_object(
        'name', c.column_name,
        'udt', c.udt_name,
        'nullable', c.is_nullable = 'YES',
        'hasDefault', c.column_default is not null or c.is_identity = 'YES'
      ) order by c.ordinal_position)
      from information_schema.columns c
      where c.table_schema = 'public' and c.table_name = tt.table_name) as columns
  from information_schema.tables tt
  where tt.table_schema = 'public' and tt.table_type = 'BASE TABLE'
) t;
`;

/** Every plain function in public with its named arguments, whether each
 * argument has a default (supabase-js: an optional Args field), and its
 * return type. Triggers, aggregates and window functions are not RPC. */
const FUNCTIONS_SQL = `
select coalesce(json_agg(f order by f.name, f.arity), '[]'::json) from (
  select p.proname as name,
    p.pronargs as arity,
    coalesce((select json_agg(json_build_object(
        'name', a.argname,
        'udt', at.typname,
        'hasDefault', a.pos > p.pronargs - p.pronargdefaults
      ) order by a.pos)
      from unnest(coalesce(p.proargnames, array[]::text[]), p.proargtypes::oid[])
        with ordinality as a(argname, typoid, pos)
      join pg_type at on at.oid = a.typoid), '[]'::json) as args,
    rt.typname as returns
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  join pg_type rt on rt.oid = p.prorettype
  where n.nspname = 'public' and p.prokind = 'f' and rt.typname <> 'trigger'
) f;
`;

export function tsTypeFor(udt) {
  // pg_type names an array type with a leading underscore (uuid[] is _uuid).
  if (udt.startsWith('_')) return `${tsTypeFor(udt.slice(1))}[]`;
  switch (udt) {
    case 'uuid':
    case 'text':
    case 'varchar':
    case 'bpchar':
    case 'timestamptz':
    case 'timestamp':
    case 'date':
      return 'string';
    case 'int2':
    case 'int4':
    case 'int8':
    case 'float4':
    case 'float8':
    case 'numeric':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'jsonb':
    case 'json':
      return 'Json';
    case 'void':
      return 'undefined';
    default:
      return 'string';
  }
}

export function renderTypes(tables, functions = []) {
  const lines = [];
  lines.push('/** Generated by scripts/db-types.mjs from the local schema.');
  lines.push(' * Do not edit by hand — run `npm run db:types` after a migration');
  lines.push(' * and commit the result; `npm run db:types:check` fails on drift. */');
  lines.push('');
  lines.push('export type Json =');
  lines.push('  | string');
  lines.push('  | number');
  lines.push('  | boolean');
  lines.push('  | null');
  lines.push('  | { [key: string]: Json | undefined }');
  lines.push('  | Json[];');
  lines.push('');
  lines.push('export interface Database {');
  lines.push('  public: {');
  lines.push('    Tables: {');
  for (const table of tables) {
    lines.push(`      ${table.table_name}: {`);
    lines.push('        Row: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      lines.push(`          ${col.name}: ${base}${col.nullable ? ' | null' : ''};`);
    }
    lines.push('        };');
    lines.push('        Insert: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      const optional = col.nullable || col.hasDefault;
      lines.push(
        `          ${col.name}${optional ? '?' : ''}: ${base}${col.nullable ? ' | null' : ''};`,
      );
    }
    lines.push('        };');
    lines.push('        Update: {');
    for (const col of table.columns) {
      const base = tsTypeFor(col.udt);
      lines.push(`          ${col.name}?: ${base}${col.nullable ? ' | null' : ''};`);
    }
    lines.push('        };');
    lines.push('        Relationships: [];');
    lines.push('      };');
  }
  lines.push('    };');
  lines.push('    Views: Record<string, never>;');
  if (functions.length === 0) {
    lines.push('    Functions: Record<string, never>;');
  } else {
    lines.push('    Functions: {');
    for (const fn of functions) {
      lines.push(`      ${fn.name}: {`);
      if (fn.args.length === 0) {
        lines.push('        Args: Record<string, never>;');
      } else {
        lines.push('        Args: {');
        for (const arg of fn.args) {
          lines.push(`          ${arg.name}${arg.hasDefault ? '?' : ''}: ${tsTypeFor(arg.udt)};`);
        }
        lines.push('        };');
      }
      lines.push(`        Returns: ${tsTypeFor(fn.returns)};`);
      lines.push('      };');
    }
    lines.push('    };');
  }
  lines.push('    Enums: Record<string, never>;');
  lines.push('    CompositeTypes: Record<string, never>;');
  lines.push('  };');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** The CLI stack's database container name, from supabase/config.toml. */
export function cliDatabaseContainer(configToml) {
  const match = /^\s*project_id\s*=\s*"([^"]+)"/m.exec(configToml);
  if (!match) return null;
  return `supabase_db_${match[1]}`;
}

/** The query travels on stdin (`-f -`), never as a command-line argument:
 * a multi-line SQL argument does not survive the Windows shell quoting
 * that `docker exec` on that platform goes through. */
const PSQL_ARGS = ['-At', '-v', 'ON_ERROR_STOP=1', '-f', '-'];

function runLocalLane(sql) {
  const args = ['-h', '127.0.0.1', '-p', PORT, '-U', PG_USER, '-d', DB, ...PSQL_ARGS];
  if (typeof process.getuid === 'function' && process.getuid() === 0) {
    return spawnSync('runuser', ['-u', PG_USER, '--', path.join(PG_BIN, 'psql'), ...args], {
      encoding: 'utf8',
      input: sql,
    });
  }
  return spawnSync(path.join(PG_BIN, 'psql'), args, { encoding: 'utf8', input: sql });
}

function runCliLane(sql) {
  const container = cliDatabaseContainer(
    readFileSync(path.join(appRoot, 'supabase', 'config.toml'), 'utf8'),
  );
  if (!container) {
    return { status: 1, stderr: 'supabase/config.toml carries no project_id' };
  }
  return spawnSync(
    'docker',
    ['exec', '-i', container, 'psql', '-U', 'postgres', '-d', 'postgres', ...PSQL_ARGS],
    { encoding: 'utf8', input: sql, shell: isWindows },
  );
}

/** The libpq environment for a connection URL: host, port, user, database
 * and password as separate variables, so the URL never has to be an
 * argument. Percent-encoding in the URL is undone here. */
export function pgEnvFromUrl(url) {
  const parsed = new URL(url);
  if (parsed.protocol !== 'postgresql:' && parsed.protocol !== 'postgres:') {
    throw new Error('HIVE_DB_URL must be a postgresql:// URL');
  }
  return {
    PGHOST: parsed.hostname,
    PGPORT: parsed.port || '5432',
    PGUSER: decodeURIComponent(parsed.username),
    PGPASSWORD: decodeURIComponent(parsed.password),
    PGDATABASE: decodeURIComponent(parsed.pathname.replace(/^\//, '')) || 'postgres',
  };
}

const PG_ENV_NAMES = ['PGHOST', 'PGPORT', 'PGUSER', 'PGPASSWORD', 'PGDATABASE'];

function runUrlLane(sql) {
  const container = cliDatabaseContainer(
    readFileSync(path.join(appRoot, 'supabase', 'config.toml'), 'utf8'),
  );
  if (!container) {
    return { status: 1, stderr: 'supabase/config.toml carries no project_id' };
  }
  const pgEnv = pgEnvFromUrl(process.env.HIVE_DB_URL);
  // `-e NAME` without a value copies the variable from this process's
  // environment into the container: the value is never on a command line.
  const passthrough = PG_ENV_NAMES.flatMap((name) => ['-e', name]);
  return spawnSync('docker', ['exec', '-i', ...passthrough, container, 'psql', ...PSQL_ARGS], {
    encoding: 'utf8',
    input: sql,
    shell: isWindows,
    env: { ...process.env, ...pgEnv },
  });
}

function chooseLane() {
  if (process.env.HIVE_DB_URL) return 'url';
  const forced = process.env.HIVE_DB_LANE;
  if (forced === 'cli' || forced === 'local') return forced;
  return existsSync(path.join(PG_BIN, isWindows ? 'psql.exe' : 'psql')) ? 'local' : 'cli';
}

const LANE_HELP = {
  url: 'db-types: could not reach the database HIVE_DB_URL names (the URL itself is never printed).',
  local:
    'db-types: could not reach the local database. Run `node scripts/db-local.mjs reset` first.',
  cli: 'db-types: could not reach the CLI stack database. Run `node scripts/local-supabase.mjs up` first.',
};

function query(sql) {
  const lane = chooseLane();
  const result =
    lane === 'url' ? runUrlLane(sql) : lane === 'local' ? runLocalLane(sql) : runCliLane(sql);
  if (result.status !== 0) {
    console.error(result.stderr ?? result.error?.message ?? '');
    console.error(LANE_HELP[lane]);
    process.exit(1);
  }
  return JSON.parse(result.stdout.trim());
}

function introspect() {
  return { tables: query(TABLES_SQL), functions: query(FUNCTIONS_SQL) };
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const command = process.argv[2];
  if (command === 'generate') {
    const { tables, functions } = introspect();
    writeFileSync(OUTPUT, renderTypes(tables, functions));
    console.log(`db-types: wrote ${path.relative(appRoot, OUTPUT)}`);
  } else if (command === 'check') {
    const { tables, functions } = introspect();
    const rendered = renderTypes(tables, functions);
    let committed = '';
    try {
      committed = readFileSync(OUTPUT, 'utf8');
    } catch {
      console.error('db-types: committed types file is missing');
      process.exit(1);
    }
    if (committed !== rendered) {
      console.error('db-types: committed database.types.ts has drifted from the schema');
      process.exit(1);
    }
    console.log('db-types: committed types match the schema');
  } else {
    console.error('usage: db-types.mjs <generate|check>');
    process.exit(1);
  }
}
