/** Generated by scripts/db-types.mjs from the local schema.
 * Do not edit by hand — run `npm run db:types` after a migration
 * and commit the result; `npm run db:types:check` fails on drift. */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      audit_receipts: {
        Row: {
          id: string;
          occurred_at: string;
          actor_user_id: string | null;
          environment_id: string;
          client_id: string;
          entity_id: string;
          action: string;
          object_ref: string;
          details: Json;
        };
        Insert: {
          id?: string;
          occurred_at?: string;
          actor_user_id?: string | null;
          environment_id: string;
          client_id: string;
          entity_id: string;
          action: string;
          object_ref: string;
          details?: Json;
        };
        Update: {
          id?: string;
          occurred_at?: string;
          actor_user_id?: string | null;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          action?: string;
          object_ref?: string;
          details?: Json;
        };
        Relationships: [];
      };
      case_attention_items: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          summary?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      case_next_actions: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          owner_role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          owner_role: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          summary?: string;
          owner_role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      cases: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          title: string;
          status: string;
          status_changed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          title: string;
          status?: string;
          status_changed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          title?: string;
          status?: string;
          status_changed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          environment_id: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          environment_id: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      entities: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          environment_id: string;
          client_id: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      environments: {
        Row: {
          id: string;
          name: string;
          kind: string;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          kind: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          kind?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          user_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          role: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
