/** Generated by scripts/db-types.mjs from the local schema.
 * Do not edit by hand — run `npm run db:types` after a migration
 * and commit the result; `npm run db:types:check` fails on drift. */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      activity_events: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          event_kind: string;
          actor_role: string;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          event_kind: string;
          actor_role: string;
          occurred_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          event_kind?: string;
          actor_role?: string;
          occurred_at?: string;
        };
        Relationships: [];
      };
      audit_receipts: {
        Row: {
          id: string;
          occurred_at: string;
          actor_user_id: string | null;
          environment_id: string;
          client_id: string;
          entity_id: string;
          action: string;
          object_ref: string;
          details: Json;
        };
        Insert: {
          id?: string;
          occurred_at?: string;
          actor_user_id?: string | null;
          environment_id: string;
          client_id: string;
          entity_id: string;
          action: string;
          object_ref: string;
          details?: Json;
        };
        Update: {
          id?: string;
          occurred_at?: string;
          actor_user_id?: string | null;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          action?: string;
          object_ref?: string;
          details?: Json;
        };
        Relationships: [];
      };
      case_attention_items: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          summary?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      case_next_actions: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          owner_role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          summary: string;
          owner_role: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          summary?: string;
          owner_role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      cases: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          title: string;
          status: string;
          status_changed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          title: string;
          status?: string;
          status_changed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          title?: string;
          status?: string;
          status_changed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          environment_id: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          environment_id: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      document_uploads: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          request_id: string;
          created_by: string;
          idempotency_key: string;
          status: string;
          display_name: string;
          mime_type: string;
          byte_size: number;
          client_digest: string;
          storage_bucket: string;
          storage_path: string;
          version: number;
          received_at: string | null;
          checked_at: string | null;
          expires_at: string;
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          request_id: string;
          created_by: string;
          idempotency_key: string;
          status?: string;
          display_name: string;
          mime_type: string;
          byte_size: number;
          client_digest: string;
          storage_bucket?: string;
          storage_path: string;
          version?: number;
          received_at?: string | null;
          checked_at?: string | null;
          expires_at: string;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          request_id?: string;
          created_by?: string;
          idempotency_key?: string;
          status?: string;
          display_name?: string;
          mime_type?: string;
          byte_size?: number;
          client_digest?: string;
          storage_bucket?: string;
          storage_path?: string;
          version?: number;
          received_at?: string | null;
          checked_at?: string | null;
          expires_at?: string;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      entities: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          display_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          environment_id: string;
          client_id: string;
          display_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          display_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      environments: {
        Row: {
          id: string;
          name: string;
          kind: string;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          kind: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          kind?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          user_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          role: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      request_answer_citations: {
        Row: {
          id: string;
          answer_id: string;
          document_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          answer_id: string;
          document_id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          answer_id?: string;
          document_id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      request_answers: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          request_id: string;
          created_by: string;
          status: string;
          body: string;
          version: number;
          submit_key: string | null;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          request_id: string;
          created_by: string;
          status?: string;
          body?: string;
          version?: number;
          submit_key?: string | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          request_id?: string;
          created_by?: string;
          status?: string;
          body?: string;
          version?: number;
          submit_key?: string | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      requests: {
        Row: {
          id: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          title: string;
          detail: string;
          owner_role: string;
          status: string;
          requested_on: string;
          due_on: string | null;
          created_at: string;
          version: number;
          subject_document_id: string | null;
        };
        Insert: {
          id?: string;
          environment_id: string;
          client_id: string;
          entity_id: string;
          case_id: string;
          title: string;
          detail: string;
          owner_role: string;
          status?: string;
          requested_on: string;
          due_on?: string | null;
          created_at?: string;
          version?: number;
          subject_document_id?: string | null;
        };
        Update: {
          id?: string;
          environment_id?: string;
          client_id?: string;
          entity_id?: string;
          case_id?: string;
          title?: string;
          detail?: string;
          owner_role?: string;
          status?: string;
          requested_on?: string;
          due_on?: string | null;
          created_at?: string;
          version?: number;
          subject_document_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      begin_document_scan: {
        Args: {
          p_upload_id: string;
        };
        Returns: Json;
      };
      begin_document_upload: {
        Args: {
          p_environment_id: string;
          p_client_id: string;
          p_entity_id: string;
          p_request_id: string;
          p_request_version: number;
          p_idempotency_key: string;
          p_display_name: string;
          p_mime_type: string;
          p_byte_size: number;
          p_client_digest: string;
        };
        Returns: Json;
      };
      complete_document_upload: {
        Args: {
          p_upload_id: string;
        };
        Returns: Json;
      };
      expire_stale_document_uploads: {
        Args: Record<string, never>;
        Returns: number;
      };
      record_document_scan: {
        Args: {
          p_upload_id: string;
          p_verdict: string;
          p_reason?: string;
        };
        Returns: Json;
      };
      save_request_answer_draft: {
        Args: {
          p_environment_id: string;
          p_client_id: string;
          p_entity_id: string;
          p_request_id: string;
          p_request_version: number;
          p_body: string;
          p_cited_document_ids: string[];
          p_answer_version?: number;
        };
        Returns: Json;
      };
      submit_request_answer: {
        Args: {
          p_answer_id: string;
          p_answer_version: number;
          p_idempotency_key: string;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
